# 넘파이 (Numpy)

## 1. 생성
### 1.1 np.arrray 

In [1]:
import numpy as np
a = np.array([1,2,3])

In [4]:
print(a)       # [1,2,3]
print(type(a)) # <class 'numpy.ndarray'>
print(len(a))  # 값 개수 - 3

[1 2 3]
<class 'numpy.ndarray'>
3


In [8]:
print(a.ndim)  # 1
print(a.shape) # (3,)
print(a.dtype) # data type - int32

1
(3,)
int32


In [57]:
a = np.array([[1,2,3], [4,5,6]], dtype = int)

In [59]:
print(a)
print(len(a)) # 2 값 개수

[[1 2 3]
 [4 5 6]]
2


In [61]:
print(a.ndim)  # 2 (axis 개수)
print(a.shape) # (2,3) - 2 rows, 3 columns
print(a.size)  # 6 (element 개수) 
print(a.dtype) # int32

2
(2, 3)
6
int32


### 1.2 np.arange

In [20]:
a = np.arange(5) # from 0 to 4
print(a) # [0,1,2,3,4]

In [22]:
print(len(a))
print(a.shape)

[0 1 2 3 4]
5
(5,)


In [32]:
a = np.arange(1,5) # from 1 to 4
print(a) #[1,2,3,4]

In [33]:
print(len(a))
print(a.shape)

[1 2 3 4]


In [110]:
a = np.arange(1,5,0.5) # from 1 to 5 by 0.5 (5 포함 X)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [66]:
a = np.linspace(0, 1, 5) # from 0 to 1, 5 elements
print(a)

In [68]:
print(len(a))

[0.   0.25 0.5  0.75 1.  ]
5


### 1.3 Initial Placeholders (zeros, ones, full,...)

In [43]:
a = np.zeros(5, dtype = int) # five (integer) zeros / default: float
print(a)

In [44]:
print(a.dtype)

[0 0 0 0 0]
int32


In [45]:
a = np.zeros((2,3)) # 2x3 zeros
print(a)

In [47]:
print(len(a))
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
2
(2, 3)


In [48]:
a = np.ones(5) # five ones
print(a)

In [50]:
print(a.dtype)

[1. 1. 1. 1. 1.]
float64


In [78]:
a = np.ones([2,3], dtype = int)
print(a)

[[1 1 1]
 [1 1 1]]


In [79]:
print(a.size)

6


In [69]:
a = np.full(5, 9) # five elements with 9
print(a) # [9,9,9,9,9]

In [70]:
print(len(a))
print(a.dtype)

[9 9 9 9 9]
5
int32


In [73]:
a = np.full((2,3), 9) # 2x3 array with 9
print(a)

In [75]:
print(len(a))
print(a.shape)
print(a.size)

[[9 9 9]
 [9 9 9]]
2
(2, 3)
6


In [82]:
a = np.eye(2, dtype = int) # 2x2 단위행렬 생성
print(a)

[[1 0]
 [0 1]]


In [87]:
np.empty((2,3)) # empty array

array([[1., 1., 1.],
       [1., 1., 1.]])

### 1.4 random

In [107]:
np.random.seed(12) # fix seed

In [108]:
np.random.randint(0,4) # an integer from 0 to 4 

3

In [111]:
np.random.randint(-3,10,10) # 10 integers from -3 to 10 (10 포함 X)

array([ 1,  2,  6, -1,  8,  3,  7, -3,  2,  5])

In [164]:
np.random.randint(0,4,(2,3)) # size는 항상 뒤에

array([[2, 3, 0],
       [1, 1, 1]])

In [114]:
np.random.random(5) # runif(5)

array([0.45605092, 0.56314114, 0.80126538, 0.94317762, 0.22335928])

In [167]:
np.random.normal(0,1,(3,3)) # N(0,1)인 3x3

array([[-0.54061424,  0.51703382, -0.54240182],
       [-0.24217533, -1.57735027,  1.06357115],
       [ 0.13808895,  0.89268377, -1.49897506]])

In [170]:
np.random.normal(3) # mean = 3인 random number 1개

3.2403512107116987

In [218]:
np.random.seed(10)
np.random.normal((2,10), (0.2,0.1), (3,2)) # 각각 N(2,0.2), N(10, 0.1)에서 3개씩 추출

[[ 2.2663173  10.0715279 ]
 [ 1.69091994  9.99916162]
 [ 2.12426719  9.92799144]]


In [186]:
np.random.randn(10) # std.normal에서 10개의 난수 생성

array([-0.96506567,  1.02827408,  0.22863013,  0.44513761, -1.13660221,
        0.13513688,  1.484537  , -1.07980489, -1.97772828, -1.7433723 ])

In [191]:
a = np.random.randn(2,3) # 표준정규분포에서 2x3 난수 생성
print(a)
print(len(a))
print(a.shape)

[[-0.33914025  0.31216994  0.56515267]
 [-0.14742026 -0.02590534  0.2890942 ]]
2
(2, 3)


In [196]:
np.random.randn((2,3)) # Error - tuple로 사이즈 지정 X

TypeError: 'tuple' object cannot be interpreted as an integer

In [199]:
a = np.random.standard_normal((2,3))
print(a)
print(a.shape)

[[-0.08112218 -0.52929608  1.04618286]
 [-1.41855603 -0.36249918 -0.12190569]]
(2, 3)


In [222]:
??np.random
# np.random.____으로 붙을 수 있는 메소드에 대한 설명

In [223]:
?np.random.RandomState

In [224]:
rng = np.random.RandomState(123) # 랜덤넘버 생성기인 랜덤함수들을 포함하는 클래스

In [228]:
rng.normal(0,1,(3,3)) # 메소드는 동일하게 사용

array([[ 1.77399501, -0.66475792, -0.07351368],
       [ 1.81403277, -0.44199761,  1.38951142],
       [-1.07746533,  0.23848917,  1.67960037]])

In [251]:
rng.randint(1,10,size=(2,3,4))

array([[[6, 2, 5, 4],
        [3, 3, 1, 3],
        [1, 3, 8, 1]],

       [[4, 8, 1, 6],
        [5, 7, 1, 8],
        [9, 9, 2, 1]]])

## 2. Subsetting, Slicing, Indexing

### 2.1 subsetting

In [274]:
# 데모 배열 생성
a0 = np.arange(1,25)       # 1차원 배열
a1 = a0.reshape((4,6))   # 2차원 배열
a2 = a0.reshape((2,4,3)) # 3차원 배열

In [275]:
print(a0)
print('---------------------------')
print(a1)
print('---------------------------')
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
---------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
---------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


#### 1차원 배열 요소 참조 및 변경

In [276]:
a0[5] # 6

6

In [278]:
# 5번 인덱스 요소 업데이트
a0[5] = 66
print(a0)

[ 1  2  3  4  5 66  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


#### 2차원 배열 요소 참조 및 변경 

In [280]:
print(a1) # a1은 a0를 참조하고 있기 때문에 a0가 바뀌면 a1도 바뀜

[[ 1  2  3  4  5 66]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [283]:
print(a1[0,1]) # 2
print(a1[0][1]) # 동일한 결과

2
2


In [285]:
a1[0,1] = 1000
print(a1)

[[   1 1000    3    4    5   66]
 [   7    8    9   10   11   12]
 [  13   14   15   16   17   18]
 [  19   20   21   22   23   24]]


#### 3차원 배열 요소 참조 및 변경

In [288]:
print(a2) # a0, a1 변경사항 모두 반영됨

[[[   1 1000    3]
  [   4    5   66]
  [   7    8    9]
  [  10   11   12]]

 [[  13   14   15]
  [  16   17   18]
  [  19   20   21]
  [  22   23   24]]]


In [294]:
print(a2[0,1,2]) #66
print(a2[0][1,2]) # 동일한 결과

66
66


### 2.2 Slicing

- 여러 개의 배열 요소를 참조할 때 사용
- 슬라이싱은 axis별로 범위를 지정하여 실행
- from_index : to_index (**from은 범위에 포함되지만 to는 포함되지 않는다**)
- from_index와 to_index는 각각 생략이 가능하며 생략될 경우 from은 0, to는 마지막을 지정한 것으로 간주된다
- from_index와 to_index에 음수를 지정하면 **반대 방향**을 의미 (ex. -1 :마지막 인덱스)

In [296]:
# 데모 배열 생성
a1 = np.arange(1,25).reshape((4,6))
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [297]:
# 가운데 요소 가져오기
a1[1:3, 1:5]

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [331]:
# 음수 인덱스를 이용한 범위 설정
# 음수 인덱스는 지정한 **axis의 마지막 요소**로부터 반대 방향의 인덱스

In [300]:
a1[1:-1, 1:-1] 

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [301]:
a1[:2, :2]

array([[1, 2],
       [7, 8]])

In [323]:
print(a1[:,2]) # 세 번째 column
print(a1[:,-1]) # 마지막 column

[ 3  9 15 21]
[ 6 12 18 24]


In [313]:
print(a1[0,:]) # 첫 번째 row
print(a1[0])

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [307]:
a1[:] # all

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [339]:
a1[::-1] # reversed

array([[19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [330]:
a1[5::-3] 
# 인덱스 숫자가 넘어가면 마지막 인덱스와 동일
# 마지막 row에서 세 칸 거꾸로

array([[19, 20, 21, 22, 23, 24],
       [ 1,  2,  3,  4,  5,  6]])

### 2.3 Boolean Indexing

In [374]:
# 데모 배열 생성
a1 = np.arange(1,25).reshape((4,6)) 
# (4,6)을 tuple로 지정하지 않아도 됨
print(a1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [364]:
# 요소의 값이 짝수인 요소 추출
even_arr = a1%2==0
even_arr

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [378]:
print(a1[even_arr])
print(a1[a1%2==0]) # same result

[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 2  4  6  8 10 12 14 16 18 20 22 24]


## 3. 배열 변환
### 3.1 reshape

In [421]:
# 1차원 배열
a = np.array([1,2,3])
print(a)
a.shape

[1 2 3]


(3,)

In [450]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [410]:
a.reshape(1,3)

array([[1, 2, 3]])

In [411]:
a.reshape(1,3).T # transpose

array([[1],
       [2],
       [3]])

In [683]:
# 2차원 배열
a1 = np.random.randint(10, size = (3,3,4))
print(a1)

[[[0 1 0 1]
  [9 4 9 0]
  [1 7 9 3]]

 [[0 8 1 5]
  [4 5 4 3]
  [4 4 1 1]]

 [[2 1 1 2]
  [2 2 5 8]
  [1 7 1 7]]]


array([2, 2, 5, 8])

In [462]:
a11 = a1.reshape(3,12)
print(a11)

[[3 6 5 5 1 8 0 5 9 8 5 7]
 [8 5 8 9 9 1 5 9 1 4 7 7]
 [7 9 7 6 0 3 9 4 4 6 8 4]]


In [464]:
a12 = a1.reshape(-1,12)
print(a12) # a11 = a12 (same result)

[[3 6 5 5 1 8 0 5 9 8 5 7]
 [8 5 8 9 9 1 5 9 1 4 7 7]
 [7 9 7 6 0 3 9 4 4 6 8 4]]


In [465]:
a13 = a1.reshape(3, -1)
print(a13) # -1 : 알아서 자동으로 계산

[[3 6 5 5 1 8 0 5 9 8 5 7]
 [8 5 8 9 9 1 5 9 1 4 7 7]
 [7 9 7 6 0 3 9 4 4 6 8 4]]


### 3.2 np.newaxis
: 새로운 축 생성 ==> 이 메서드가 들어가는 자리에 1

In [428]:
x = a[np.newaxis,:] # row에 새로운 축 생성(2차원 행벡터화)
print(x,"," ,x.shape)

[[1 2 3]] , (1, 3)


In [429]:
x = a[:, np.newaxis] # column에 새로운 축 생성(2차원 열벡터화)
print(x,",",x.shape)

[[1]
 [2]
 [3]] , (3, 1)


In [466]:
# 2차원 배열
a1

array([[[3, 6, 5, 5],
        [1, 8, 0, 5],
        [9, 8, 5, 7]],

       [[8, 5, 8, 9],
        [9, 1, 5, 9],
        [1, 4, 7, 7]],

       [[7, 9, 7, 6],
        [0, 3, 9, 4],
        [4, 6, 8, 4]]])

In [468]:
x1 = a1[np.newaxis,:]  #(1, origial shape)-> (1,4,6)
print(x1,",",x1.shape) 

[[[[3 6 5 5]
   [1 8 0 5]
   [9 8 5 7]]

  [[8 5 8 9]
   [9 1 5 9]
   [1 4 7 7]]

  [[7 9 7 6]
   [0 3 9 4]
   [4 6 8 4]]]] , (1, 3, 3, 4)


In [469]:
x2 = a1[:, np.newaxis] # (original shape, 1) -> (4,6,1)
print(x2, ",", x2.shape)
# (4,1,6)으로 바뀌는 것에 주의

[[[[3 6 5 5]
   [1 8 0 5]
   [9 8 5 7]]]


 [[[8 5 8 9]
   [9 1 5 9]
   [1 4 7 7]]]


 [[[7 9 7 6]
   [0 3 9 4]
   [4 6 8 4]]]] , (3, 1, 3, 4)


### 3.3 분할 (np.split)
※ np.split만 허용

In [473]:
x = np.arange(1,9)
print(x)

[1 2 3 4 5 6 7 8]


In [492]:
x1, x2 = np.split(x,2) # 두 개(equal size)로 쪼개기 + unpacking
print(x1, x2)

[1 2 3 4] [5 6 7 8]


In [498]:
np.split(x,[2,3]) # [:2][2:3][3:]

[array([1, 2]), array([3]), array([4, 5, 6, 7, 8])]

In [499]:
np.split(x, [2,-1]) # [:2][2:-1][-1:]

[array([1, 2]), array([3, 4, 5, 6, 7]), array([8])]

#### vsplit, hsplit

In [501]:
x = np.random.randint(10, size = (4,4))
print(x)

[[8 2 2 0]
 [1 2 3 5]
 [7 8 7 7]
 [6 9 2 0]]


In [506]:
x1, x2 = np.vsplit(x, 2) # vertically (np.vsplit(x,[2]))
print(x1)
print('--------------------------------------------------')
print(x2)

[[8 2 2 0]
 [1 2 3 5]]
--------------------------------------------------
[[7 8 7 7]
 [6 9 2 0]]


In [589]:
x1, x2 = np.split(x,2) # (row-wise, axis = 0)
print(x1)
print('--------------------------------------------------')
print(x2)

[[8 2 2 0]
 [1 2 3 5]]
--------------------------------------------------
[[7 8 7 7]
 [6 9 2 0]]


In [586]:
x1, x2 = np.split(x, 2, axis=1)
print(x1)
print('--------------------------------------------------')
print(x2)

[[8 2]
 [1 2]
 [7 8]
 [6 9]]
--------------------------------------------------
[[2 0]
 [3 5]
 [7 7]
 [2 0]]


In [593]:
x1, x2 = np.hsplit(x, 2) # column-wise
print(x1)
print('--------------------------------------------------')
print(x2)

[[8 2]
 [1 2]
 [7 8]
 [6 9]]
--------------------------------------------------
[[2 0]
 [3 5]
 [7 7]
 [2 0]]


### 3.4 덧붙이기

In [600]:
x = np.array([1,2])
y = np.array([2,3])
z = np.array([4,5])
np.concatenate([x,y,z])

array([1, 2, 2, 3, 4, 5])

In [608]:
xx = np.array([[1,2,3],[4,5,6]])
yy = np.array([[2,4,6],[8,7,6]])

In [606]:
# 아래로 붙이기 (axis=0, row-wise)
print(np.concatenate([xx,yy])) 

[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]


In [607]:
# 옆으로 붙이기 (axis=1, column-wise)
print(np.concatenate([xx,yy], axis = 1)) 

[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]


In [627]:
# 세로로 쌓기
zz = np.array([55,66,77])
np.vstack([xx,zz])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [55, 66, 77]])

In [612]:
# 가로로 쌓기
ww = np.array([[100],[200]])
np.hstack([ww,xx])

array([[100,   1,   2,   3],
       [200,   4,   5,   6]])

In [637]:
# np.stack은 shape가 모두 동일해야 함
np.stack([zz,zz],axis=1)

array([[55, 55],
       [66, 66],
       [77, 77]])

## 4. 연산
### 4.1 기본 연산

In [639]:
x = np.array([1, 2, 3, 4])
print(x+3)
print(x-3)
print(x*3)
print(x%3)  # 나머지
print(x**3) # 제곱
print(-(0.5*x+1)**2)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[1 2 0 1]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [640]:
print(np.exp(x))
print(np.power(3, x)) # 3^x
print(np.log(x))
print(np.log2(x))
print(np.log10(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 3  9 27 81]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [643]:
M = np.ones((3,3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [645]:
a = np.array([2,3,4])
M+a # row by row로 연산 수행

array([[3., 4., 5.],
       [3., 4., 5.],
       [3., 4., 5.]])

In [652]:
# Broadcast
a = np.arange(3) # [0,1,2]
b = np.arange(3)[:,np.newaxis] # shape = (3,1) 
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [666]:
# Broadcasting 작동 원리
np.vstack([a,a,a]) + np.hstack([b,b,b])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 4.2 기초 통계량
- axis = 0 : row-wise ------> 이런 진행방향, 각 열별
- axis = 1 : column-wise | 아래로 떨어지는 진행방향, 각 행별

In [2]:
import numpy as np
x = np.random.randint(10, size = (3,4))
print(x)

[[7 9 0 0]
 [5 5 3 4]
 [4 8 0 2]]


In [3]:
print(np.sum(x)) # 원소의 총 합계
print(np.sum(x, axis = 1)) # 각 행의 최솟값
print(np.mean(x, axis = 0)) # 각 열의 평균
print(np.std(x, axis = 0)) # 각 열의 표준편차

47
[16 17 14]
[5.33333333 7.33333333 1.         2.        ]
[1.24721913 1.69967317 1.41421356 1.63299316]


In [673]:
x = np.arange(12).reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [677]:
y1 = np.array([1,2,2])
print(y1[:,np.newaxis])

[[1]
 [2]
 [2]]


In [678]:
y2 = np.array([2,0,1])
print(y2)

[2 0 1]


In [679]:
x[y1,y2]

array([6, 8, 9])

In [680]:
# 브로드캐스팅
print(x[y1[:,np.newaxis], y2])

[[ 6  4  5]
 [10  8  9]
 [10  8  9]]
